CREATE TABLE [dbo].[Options]
(
		[RowId]			INT					NOT NULL	IDENTITY(1,1)					PRIMARY KEY
	,	[Id]			UNIQUEIDENTIFIER	NOT NULL	DEFAULT(NEWSEQUENTIALID())
	,	[Field]			INT					NOT NULL
	,	[Text]			NVARCHAR(128)		NOT NULL
	,	[Value]			NVARCHAR(128)		NOT NULL
)
